dist: trusty
language: node_js
node_js: 6.10.2
notifications:
  email: false
deploy:
  provider: npm
  email: briancruddy@gmail.com
  api_key:
    secure: O323OBJDiDYPYpRlLNgHEo2sTbKBi0uC/EubzBhcUdonhV8zOUYXsmhxWsfYLPSYJDl/KmHTP2XMi1fvFU4HJ9rWrpx79iUYm35J4UKfo5PGJan//3nvtKKfTYL2F+XmiLQgRbLaLOBnh/QM6icw5gXCSNRy6Hf1SAMXLcBUL2HZABYtyU43Ta1MseqkVoOPlEKRWQfl6Hpr2x1+WvfJ6yamH7FcdHWwnouGRgdDZK7/BvSb2myucd6HoVntQ4Jf7U+80D2qyLsbPegqBfuDzuVwAkGrO/g16qpjnu6aFlPc6/h0EEeAejGv1pzY8sWzDG5QipqtX6tpSFdIHQL3Or+dJ2gF58s3SR09oyVALrSdY2DhLgCCktdbXe/wm/LnOcsF4ul/CIJujDAGgAN03FywREIRBfgzrEedoqBMrx0u6dh1IgONxDtJ8cnkCistrr7cL1HTkdouVDEgWFi1vxF4OswoRuYFKQS8sHYK+wgoDORZHdo+2ptsSULAJoc1u7q5/Xbeoy5U/zQxeCqFb2iQifhVUs1jvQbGm8HCiJ0ypN4TIwGEqk2Xz6jn9G8qwn/P8laT2E4c9sYRNUvqThnC745gydRJXy/11MyX4WzzcVaP2e375i39uh6KPqJT9k8CQ5+IjSqRWiy7Bnok7j7oEfYVfQd3smG9QuRk5MI=
  on:
    branch: master
    repo: bcruddy/express-url-cleaner
